-- ВАЖНО, не забудь добавить условия product_id, тк это все только для кредитки

-- LAYOUT_OVERLAYS
-- 1. Overlay для вопросов
-- 2. Overlay для онбординга credit_limit
-- 3. Overlay для онбординга cashback

-- LAYOUT_SECTIONS
-- 1. Секция для вопросов credit_card_info_general
-- 2. Секция для вопросов credit_card_info_grace
-- 3. Секция для вопросов credit_card_info_cashback
-- 4. Секция для вопросов credit_card_info_limit
-- 5. Секция для вопросов credit_card_info_min
-- 6. Секция для онбординга i_credit_limit_grace
-- 7. Секция для онбординга i_credit_limit_grace_duration
-- 8. Секция для онбординга i_credit_limit_grace_duration
-- 9. Секция для онбординга i_cashback_whatis
-- 10. Секция для онбординга i_cashback_earn
-- 11. Секция для онбординга i_cashback_spend

-- LAYOUT_WIDGETS
-- 1. Виджет для списка вопросов collapse_list_credit_card_info_general
-- 2. Виджет для списка вопросов collapse_list_credit_card_info_grace
-- 3. Виджет для списка вопросов collapse_list_credit_card_info_cashback
-- 4. Виджет для списка вопросов collapse_list_credit_card_info_limit
-- 5. Виджет для списка вопросов collapse_list_credit_card_info_min
-- 6. Виджет для слайда онбординга intro_block_grace
-- 7. Виджет для слайда онбординга intro_block_grace_duration
-- 8. Виджет для слайда онбординга intro_block_grace_benefit
-- 9. Виджет для слайда онбординга intro_block_cashback_whatis
-- 10. Виджет для слайда онбординга intro_block_cashback_earn
-- 11. Виджет для слайда онбординга intro_block_cashback_spend

-- LAYOUT_ACTIONS
-- 1. Действие на открытие overlay credit_card_info

-- LAYOUT_RENDERING
-- 1. Рендеринг для картинки img_box
-- 2. Рендеринг для кнопки accent_primary_standard

-- LAYOUT_COMPONENTS
-- 0. Компонент для кнопки информации по кредитке row_action row_action_credit_card_info
-- 0. Компонент для вопроса credit_card_q1
-- 0. Компонент для вопроса credit_card_q2
-- 0. Компонент для вопроса credit_card_q3
-- 0. Компонент для вопроса credit_card_q4
-- 0. Компонент для вопроса credit_card_q5
-- 0. Компонент для вопроса credit_card_q6
-- 0. Компонент для вопроса credit_card_q7
-- 0. Компонент для вопроса credit_card_q8
-- 0. Компонент для вопроса credit_card_q9
-- 0. Компонент для вопроса credit_card_q10
-- 0. Компонент для вопроса credit_card_q11
-- 0. Компонент для вопроса credit_card_q12
-- 0. Компонент для вопроса credit_card_q13
-- 0. Компонент для вопроса credit_card_q14
-- 0. Компонент для вопроса credit_card_q15
-- 0. Компонент для вопроса credit_card_q16
-- 0. Компонент для вопроса credit_card_q17
-- 0. Компонент для вопроса credit_card_q18
-- 0. Компонент для вопроса credit_card_q19
-- 0. Компонент для вопроса credit_card_q20
-- 0. Компонент для вопроса credit_card_q21
-- 0. Компонент для вопроса credit_card_q22
-- 0. Компонент для вопроса credit_card_q23
-- 0. Компонент для вопроса credit_card_q24
-- 0. Компонент для вопроса credit_card_q25
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
-- 0. Компонент для 
