/*
TODO:
- Дополнить миграцией всех текущих оферт.
*/

CREATE TABLE OFFERS_V1
(
    id                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    title             VARCHAR2(255) NOT NULL,
    description       VARCHAR2(255) NULL,
    state             VARCHAR2(255) DEFAULT 'active' NOT NULL, -- active|archive
    sort_order        NUMBER(10) DEFAULT 100 NOT NULL, -- In case there are two offers for a single spot
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT OFFERS_V1_PK PRIMARY KEY (id)
);
CREATE TABLE USERS_OFFERS
(
    id                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    user_id           NUMBER(10) NOT NULL, -- FK: USERS.ID
    offer_version_id  NUMBER(10) NOT NULL, -- FK: OFFERS_VERSIONS.ID
    user_device_id    NUMBER(10) NOT NULL, -- FK: USERS_DEVICES.ID
    meta              CLOB NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USERS_OFFERS_PK PRIMARY KEY (id)
);
CREATE INDEX IDX_USERS_OFFERS_USER_OFFER ON USERS_OFFERS (user_id, offer_version_id);
CREATE TABLE OFFERS_VERSION
(
    id                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    offer_id          NUMBER(10) NOT NULL, -- FK: OFFERS_V1.ID
    file_uz           VARCHAR2(255) NOT NULL,
    file_ru           VARCHAR2(255) NOT NULL,
    file_en           VARCHAR2(255) NOT NULL,
    dated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, -- Scheduling mechanism, from this time a version is going to be forced to accept
    outdated_at       TIMESTAMP NULL, -- Scheduling mechanism, from this time a version is not forced to accept
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT OFFERS_VERSION_PK PRIMARY KEY (id)
);
CREATE TABLE OFFER_TRIGGERS
(
    id                NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    offer_id          NUMBER(10) NOT NULL,
    is_active         CLOB NULL, -- \request obj. is passed, expanding it as needed: '{"call_func":"vd_paninfo"}'
    is_triggered      NUMBER(1), -- 0|1, either trigger's is_active going to be checked or not
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT OFFER_TRIGGERS_PK PRIMARY KEY (id)
);
