-- TODO: Провалидируй все sql на корректность с Oracle v19
-- TODO: Посмотри остальные таблицы Заказа карты 2.0 и если что дай добро использовать их без холда, но контракты запросов точно обновятся

/*
Tables:
CARD_PRODUCTS_V1
CARD_PRODUCTS_V1_TEXTS
TAGS
TAG_RELATIONS

Disclaimer:
Здесь таблицы связанные только с каталогом и деталями. Убедительная просьба проверить корректность.
*/

CREATE TABLE CARD_PRODUCTS_V1 {
    ID                       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    PRODUCT_CODE             VARCHAR(50) NULL, /** 870, 860, 840, ... */
    COMMISSION               VARCHAR(50) NULL, /** IDENTIFICATOR COMMISSION FOR ISSUE CARD */
    HAS_CUSTOM_DESIGN        NUMBER(1) DEFAULT 0 NOT NULL, /** 0|1 */
    CUSTOM_DESIGN_COMMISSION VARCHAR(50) NULL, /** IDENTIFICATOR COMMISSION FOR ISSUE CARD */
    CUSTOM_DESIGN_CODE       VARCHAR(50) NULL, /** CUSTOM DESIGN CODE: 036, 037, ... */
    STATE                    NUMBER(1) DEFAULT 0 NOT NULL, /** 0|1|2 */
    BACKGROUND               VARCHAR(250) NULL, /** image url */
    LOGOS_LAYER              VARCHAR(250) NULL, /** image url */
    WEBVIEW                  VARCHAR(250) NULL, /** webview url */
    EMBOSS_TYPE              VARCHAR(50) NOT NULL, /** uzcard|humo|tieto */
    IS_VIRTUAL               NUMBER(1) DEFAULT 0 NOT NULL, /** 0|1 */
    TYPE_APPLICATION         VARCHAR(50) NOT NULL, /** uzcard_issue, humo_issue, humovirtual, visa_issue */
    SORT_ORDER               NUMBER(10) DEFAULT 100 NOT NULL, /** sort order ascending order */
    CURRENCY                 VARCHAR(50) DEFAULT 'UZS' NOT NULL, /** Card currency */
    PRICE                    VARCHAR(250) NOT NULL, /** card price in cents */
    CARD_IMAGE               VARCHAR(250) NOT NULL, /** card image url */
    BACKGROUND_COLOR         VARCHAR(250) NOT NULL, /** card background color of card (page_background_color) */
    HEADER_COLOR             CLOB NULL, /** card background color of card (widget) */
    CREATED_AT               TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT               TIMESTAMP DEFAULT SYSDATE,
    DELETED_AT               TIMESTAMP NULL,
    CONSTRAINT CARD_PRODUCTS_V1_PK PRIMARY KEY (ID)
}
CREATE TABLE CARD_PRODUCTS_V1_TEXTS {
    ID                       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    CARD_PRODUCT_ID          NUMBER(10) NOT NULL, /** Foreign key from table card_products_v1 id */
    LANGUAGE                 VARCHAR(3) NOT NULL, /** uz|ru|en */
    TITLE                    VARCHAR(250) NOT NULL, /** title of the product - */
    DESCRIPTION              CLOB NOT NULL, /** description of product - */
    ICON_ID                  VARCHAR(250), /** FK - ICONS.ID */
    TYPE                     VARCHAR(250) NOT NULL, /** collapse, text, etc. */
    SORT_ORDER               NUMBER(10) DEFAULT 100 NOT NULL,
    RENDER_ID                VARCHAR(250) NULL, /** FK - LAYOUT_RENDERS.ID */
    ACTION_ID                VARCHAR(250) NULL, /** FK - LAYOUT_ACTIONS.ID */
    CREATED_AT               TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT               TIMESTAMP DEFAULT SYSDATE,
    DELETED_AT               TIMESTAMP NULL,
    CONSTRAINT CARD_PRODUCTS_V1_TEXTS_PK PRIMARY KEY (ID)
}
CREATE TABLE TAGS {
    ID                       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    NAME                     VARCHAR(250) NOT NULL,
    TYPE                     VARCHAR(50) NOT NULL,
    "GROUP"                  VARCHAR(50) NULL,
    SORT_ORDER               NUMBER(10) DEFAULT 100 NOT NULL,
    IS_PRIMARY               NUMBER(1) DEFAULT 0 NOT NULL, /** 0|1 */
    STATE                    NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT               TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT               TIMESTAMP DEFAULT SYSDATE,
    DELETED_AT               TIMESTAMP NULL,
    CONSTRAINT TAGS_PK PRIMARY KEY (ID)
}
CREATE TABLE TAG_RELATIONS {
    ID                       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE NOT NULL,
    TAG_ID                   NUMBER(10) NOT NULL,
    TARGET_ID                NUMBER(10) NOT NULL,
    TARGET                   VARCHAR(250) NOT NULL,
    RENDER_ID                VARCHAR(250) NULL, /** FK - LAYOUT_RENDERS.ID */
    CREATED_AT               TIMESTAMP DEFAULT SYSDATE,
    UPDATED_AT               TIMESTAMP DEFAULT SYSDATE,
    CONSTRAINT TAG_RELATIONS_PK PRIMARY KEY (ID)
}
CREATE INDEX TAG_RELATIONS_IDX_TARGET ON TAG_RELATIONS (TARGET, TARGET_ID);
CREATE INDEX TAG_RELATIONS_IDX_TAG ON TAG_RELATIONS (TAG_ID);
