@startuml v1/cards/byphone - Этап 3
actor       "Пользователь"    as User
participant "МП IYM"          as App
participant "IYM Backend"     as BE
participant "Redis"           as Redis
participant "DB.MOBILEN"      as DB
participant "Процессинг"      as Processing

note over App
    Этап 3:
    - Возвращаем все карты IYB, Uzcard, HUMO
    - Отсутствие пользователя не останавливает флоу
    - Отсутствие карт IYB не останавливает флоу
    * Механики те же самые
    * [!] Реализуется после токенизации
end note

User -> App : Перевод на карту
        activate User
        activate App
User <- App : Экран перевода
        deactivate User
        deactivate App
==v1/card/byphone==
User -> App : По номеру телефона
        activate User
        activate App
User <- App : Форма ввода номера
User -> App : 998XXXXXXXXX
App -> BE : **v1/card/byphone**
        activate BE
==Банки и префиксы==
BE -> Redis : cards_byphone_banks
        activate Redis
BE -> Redis : cards_byphone_bank_card_prefixes
alt Ключ есть
    BE <- Redis : Банки
    BE <- Redis : Префиксы
        deactivate Redis
else Ключа нет
    BE -> DB : Записи BANKS
        activate DB
    BE -> DB : Записи BANK_CARD_PREFIXES
    BE <- DB : Банки
    BE <- DB : Префиксы
        deactivate DB
    BE -> Redis : cards_byphone_banks, 24ч
        activate Redis
    BE -> Redis : cards_byphone_bank_card_prefixes, 24ч
        deactivate Redis
end
==IYB карты==
BE -> DB : Запросить user по phone
        activate DB
alt user найден
    BE <- DB : Пользователь
    BE -> DB : Крайний users_cards.updated_at \nэтого пользователя
    BE <- DB : Последнее обновление
    BE -> Redis : cards_byphone_iyb_{{phone}}_{{updated_at}}
        activate Redis
    alt Ключ есть
    BE <- Redis : Карты IYB
        deactivate Redis
    else Ключа нет
        BE -> DB : Карты пользователя
        note over DB #SkyBlue
            STATE=active
            TYPE=visa
        end note
        BE <- DB : Карты IYB
        loop Карты IYB
            BE -> Processing : getCardHolderByPan
        activate Processing
            BE <- Processing : Имя на карте
        deactivate Processing
        end
        BE -> Redis : cards_byphone_iyb_{{phone}}_* \nУдалить
        BE -> Redis : cards_byphone_iyb_{{phone}}_{{updated_at}} \nКарты IYB
    end
    BE -> BE : Карты IYB -> Карты
else user не найден
    BE <- DB : (empty)
        deactivate DB
end
==Карты Uzcard==
BE -> Redis : cards_byphone_uzcard_{{phone}}
activate Redis
alt Ключ есть
    BE <- Redis : Карты Uzcard
        deactivate Redis
else Ключа нет
    BE -> Processing : cards.list.tokens
        activate Processing
    BE <- Processing : Карты Uzcard
        deactivate Processing
    loop Карты Uzcard
        BE -> Processing : p2p.info
        activate Processing
        BE <- Processing : PAN карты
        deactivate Processing
    end
    BE -> Redis : cards_byphone_uzcard_{{phone}} \nКарты Uzcard, 1ч
end
loop Карты Uzcard
    BE -> BE : [Процесс: Токенизация карты]
end
BE -> BE : Карты Uzcard -> Карты
==Карты HUMO==
BE -> Redis : cards_byphone_humo_{{phone}}
activate Redis
alt Ключ есть
    BE <- Redis : Карты HUMO
        deactivate Redis
else Ключа нет
    BE -> Processing : /v2/mb/customer-list
        activate Processing
    BE <- Processing : Карты HUMO
        deactivate Processing
    BE -> Redis : cards_byphone_humo_{{phone}} \nКарты HUMO, 1ч
end
loop Карты HUMO
    BE -> BE : [Процесс: Токенизация карты]
end
BE -> BE : Карты HUMO -> Карты
==Связка с банками==
loop Карты
    BE -> BE : Банк по префиксу
end
App <- BE : Список карт
        deactivate BE
User <- App : Выбор карты
        deactivate User
        deactivate App

@enduml
